language: node_js
node_js:
- 8
before_install:
- npm i -g npm@5.3.0
deploy:
  provider: heroku
  api_key:
    secure: QMbPRYSsiBtOyaviUx1ETXFXJjqGKSZHyNlVSOkneX97HdHRi+reEmyB90JQuPUsKl3cOtGwTyyNgYPm5Jgrx1rTJv2UMX81/98XUvBIvF2r9aOAUAIjjI+hEbCOgm0m0u1G33Y+R0kpFb8chBLCh6ysfiUY9Hpt9OSPWtVXCEVFwMdHbjgcLHO9X1iV7NCSN2KzY7g6jrPK7eVINEl7xU25rMFg2+UAEeYK/VS2hTMrEf6kjhR+oypd/GBzm1apnGFkmuGvnQFfXc4nfBiKXEX8ErRF059EBD6rqvhs+myYraEquK0YFn7y/kOyCaMxG3ki4klnmtPM/T27kumUMpZr9a5uItx1td2OHKaeORTbC6Y46gqiYnXrfUUDuRoDJWJ3R7i9Cn9cpwZXo1kUQpdu1rZNw/AsfSJZj/NXmdIxWdYbelkz0t8FDxgaUbbE5wl+WTwojYzUA8a8lc/u49B7W1NqRawfmLuMorRjhTydlYMzrevzUP8+Isw7x6wv+x9uxJIrv85VMjDkR5S6ekKZYEqPBfeHFdXUmVZisyMC1TT1+2WsG+kqPB7farIl9fqs6TfomZkwLCUo23tKr8y5GsIMz1QfaCBGBA0UQDQIUHoUh7f/AVbZq0OgIDTTRNu5ILUwpebP3mGkQ8afjdeWzp5vbEfmtg8i+rJ9DyQ=
  app: opentable-app
  on:
    repo: ericbastarache/opentable-app
    branch: develop
script:
- yarn build
cache:
  directories:
  - node_modules
notifications:
  email: false
